remotes::install_github("OHDSI/DataQualityDashboard")
library(DataQualityDashboard)

# Mac/Linux: Path Example: /Users/cpu/Downloads/OMOP/
# Windows: Path Example: D:\\LoF\\omop\\
# create database connection
cd <- DatabaseConnector::createConnectionDetails(
  dbms     = "postgresql",
  server   = "localhost/omop",
  user     = "postgres",
  password = "admin123",
  port     = 5432,
  pathToDriver = "/path_to_omop_folder/"  # path to your OMOP folder
)

# Mac/Linux: outputFolder Example: /Users/cpu/Downloads/OMOP/output
# Windows: outputFolder Example: D:\\LoF\\omop\\output
cdmDatabaseSchema = 'omop.cdm54'
resultsDatabaseSchema='omop.results'
cdmSourceName='omop.synthea'
outputFolder = '/path_to_omop_folder/output' # create output folder

executeDqChecks(connectionDetails=cd, cdmDatabaseSchema, 
                resultsDatabaseSchema, outputFolder=outputFolder, 
                cdmSourceName=cdmSourceName, cdmVersion="5.4", outputFile = "file.json")

# give path to actual json file to view
viewDqDashboard('/Users/cpu/Downloads/OMOP/output/file.json') # this should be the filepath to the json generated by executeDqChecks
